import {createServerClient} from '@supabase/ssr';
import {parseCookieHeader,serializeCookieHeader} from '@supabase/ssr';
import {runtime,statement} from './database';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function configured(){const e=runtime();return !!(e.SUPABASE_URL&&e.SUPABASE_PUBLISHABLE_KEY)}
export function authClient(request:Request,out:Headers){if(!configured())throw new HttpError(503,'Đăng nhập Google/email chưa được thiết lập.');const e=runtime();return createServerClient(e.SUPABASE_URL,e.SUPABASE_PUBLISHABLE_KEY,{cookieOptions:{httpOnly:true,secure:true,sameSite:'lax',path:'/'},cookies:{getAll:()=>parseCookieHeader(request.headers.get('cookie')||'').map(x=>({name:x.name,value:x.value||''})),setAll:cs=>{for(const c of cs)out.append('Set-Cookie',serializeCookieHeader(c.name,c.value,{...c.options,httpOnly:true,secure:true,sameSite:'lax',path:'/'}))}}})}
export async function identity(request:Request,out:Headers,required=true){if(!configured()){if(required)throw new HttpError(503,'Đăng nhập Google/email chưa được thiết lập.');return null}const client=authClient(request,out);const {data,error}=await client.auth.getUser();if(error||!data.user){if(required)throw new HttpError(401,'Vui lòng đăng nhập để tiếp tục.');return null}const u=data.user;if(!u.email_confirmed_at)throw new HttpError(403,'Vui lòng xác minh email trước khi tiếp tục.');await statement('INSERT INTO users(id,email,name,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name',u.id,u.email||'',String(u.user_metadata?.full_name||'').slice(0,100),Date.now()).run();const adminEmail=String(runtime().ECOSNAP_ADMIN_EMAIL||'').trim().toLowerCase();if(adminEmail&&u.email?.toLowerCase()===adminEmail)await statement("UPDATE users SET role='admin' WHERE id=?",u.id).run();return await statement('SELECT id,email,name,role FROM users WHERE id=?',u.id).first<any>()}
export async function requireAdmin(request:Request,out:Headers){const u=await identity(request,out);if(u.role!=='admin')throw new HttpError(403,'Bạn không có quyền quản trị.');return u}
export function checkOrigin(req:Request){if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.get('origin');if(origin!=='https://ecosnap.trangphamhp2004.chatgpt.site'&&origin!==new URL(req.url).origin)throw new HttpError(403,'Nguồn yêu cầu không hợp lệ.');if(req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Nguồn yêu cầu không hợp lệ.')}}
export const baseURL='https://ecosnap.trangphamhp2004.chatgpt.site';
export function safeReturn(p:unknown){return typeof p==='string'&&/^\/(scan|explore|account|item\/[a-zA-Z0-9_-]+|admin|reset)$/.test(p)?p:'/account'}
