import {normalizeSearch} from '../sorting-rules';
import type {ProductContext} from '../product-label';
export const PRODUCT_REVIEW_DATE='2026-10-03';
const expiry=Date.parse('2027-01-01T00:00:00+07:00');
// Versioned, source-reviewed data. No model text or client-supplied URLs enter advice.
export function productGuidance(p:ProductContext,ids:string[],now=Date.now()){
 const brand=normalizeSearch(p.brand).replace(/[^a-z0-9]/g,''),name=normalizeSearch(p.productName).trim(),variant=normalizeSearch(p.variant).replace(/\s/g,'');
 const safe=p.remaining==='empty'&&p.warning==='none'&&!ids.some(id=>id.startsWith('hazard')||['battery','lamp','electronics','unknown-liquid','product-residue','drink-residue'].includes(id));
 const references:{title:string;body:string;source:string}[]=[];
 const programs:{title:string;scope:string;steps:string[];source:string;checkedAt:string}[]=[];
 if(now<expiry&&brand==='cocoon'&&name==='sua rua mat sen hau giang'&&variant==='500ml'&&p.packageForm==='bottle'&&['unknown','PET 1'].includes(p.materialCode)&&ids.includes('bottle'))references.push({title:'Thông tin đúng phiên bản sản phẩm',body:'Cocoon giới thiệu chai Sữa rửa mặt sen Hậu Giang 500 ml bằng PET tái chế 100%. Thông tin này chỉ nói về thân chai; chưa xác định vật liệu nắp/vòi và không áp dụng cho túi refill hay dung tích khác.',source:'https://www.cocoonvietnam.com/'});
 if(now<expiry&&safe&&brand==='cocoon'&&['bottle','jar'].includes(p.packageForm)&&ids.some(id=>['bottle','glass'].includes(id))&&!ids.includes('glass-broken'))programs.push({title:'Cocoon · Điểm xanh online 2026',scope:'Gợi ý chương trình của thương hiệu cho chai/hũ Cocoon đã dùng hết. Chưa xác nhận cửa hàng hay mọi phiên bản đều tiếp nhận.',steps:['Giữ tem nhãn; vỏ gửi đi cần rỗng, sạch và không biến dạng. Có thể thiếu nắp.','Mở trang chương trình để kiểm tra điều kiện hiện hành và đăng ký trước khi gửi. Người gửi chịu phí vận chuyển đến kho.'],source:'https://www.cocoonvietnam.com/bai-viet/diem-xanh-online-cung-cocoon-song-xanh-moi-ngay-2026',checkedAt:PRODUCT_REVIEW_DATE});
 if(now<expiry&&safe&&['loccitane','loccitaneenprovence'].includes(brand)&&p.packageForm==='tube'&&p.materialCode==='ALU'&&/^(kem (duong (da )?)?tay( bo dau mo)?|shea butter hand cream|shea hand cream)$/.test(name)&&ids.includes('metal'))programs.push({title:'L’Occitane · Big Little Things',scope:'Chỉ vỏ tuýp kem tay nhôm L’Occitane đã được bạn xác nhận; không áp dụng cho mọi tuýp hoặc thương hiệu khác.',steps:['Liên hệ cửa hàng để xác nhận tiếp nhận tuýp đã dùng hết. Hãng yêu cầu sạch và khô.','Hỏi cửa hàng cách mở/làm sạch tuýp an toàn; EcoSnap không hướng dẫn tự cắt nhôm. Xem điều kiện và lịch nhận tại trang chính thức.'],source:'https://vn.loccitane.com/pages/big-little-things',checkedAt:PRODUCT_REVIEW_DATE});
 return {checkedAt:PRODUCT_REVIEW_DATE,references,programs,message:now>=expiry?'Thông tin hãng đã đến hạn kiểm tra lại. Hãy mở nguồn chính thức hoặc hỏi hãng; chưa áp dụng tự động.':!references.length?'Chưa có hồ sơ khớp chính xác tên, phiên bản và bao bì này. Phân loại ở trên dựa vào các phần bạn xác nhận; không suy chất liệu từ thương hiệu.':'Thông tin hãng bổ sung cho đúng phiên bản; cách bỏ từng phần vẫn theo hướng dẫn đã kiểm duyệt.'};
}
