import {statement} from './database';
import {HttpError} from './auth';
export async function boundedBody(req:Request,max:number){if(Number(req.headers.get('content-length')||0)>max)throw new HttpError(413,'Dữ liệu quá lớn.');const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let length=0;for(;;){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();throw new HttpError(413,'Dữ liệu quá lớn.')}chunks.push(value)}const body=new Uint8Array(length);let offset=0;for(const chunk of chunks){body.set(chunk,offset);offset+=chunk.length}return body}
export async function json(req:Request){if(!req.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'Định dạng yêu cầu không hợp lệ.');const body=await boundedBody(req,100000);try{return JSON.parse(new TextDecoder().decode(body))}catch{throw new HttpError(400,'Dữ liệu không hợp lệ.')}}
export function password(v:unknown){if(typeof v!=='string'||!v.length||v.length>128)throw new HttpError(400,'Mật khẩu không hợp lệ.');return v}
export function str(v:unknown,max:number,required=true){if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw new HttpError(400,'Vui lòng kiểm tra các trường bắt buộc và độ dài nội dung.');return v.trim()}
export function number(v:unknown,min:number,max:number){if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)throw new HttpError(400,'Giá trị số không hợp lệ.');return v}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function limit(key:string,max:number,windowMs:number){const at=Date.now(),slot=Math.floor(at/windowMs),k=await digest(key+':'+slot);const result=await statement('INSERT INTO rate_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count<? RETURNING count',k,at+windowMs,max).first();if(!result)throw new HttpError(429,'Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau.');if(Math.random()<.01)await statement('DELETE FROM rate_limits WHERE expires_at<?',at).run()}
export async function validateFile(file:File){if(file.size>5*1024*1024||!file.size)throw new HttpError(400,'Tệp phải có dung lượng từ 1 byte đến 5 MB.');const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer());const signatures:Record<string,boolean>={'image/jpeg':bytes[0]===255&&bytes[1]===216&&bytes[2]===255,'image/png':bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10','application/pdf':new TextDecoder().decode(bytes.slice(0,5))==='%PDF-','image/webp':new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'};if(!signatures[file.type])throw new HttpError(400,'Chỉ nhận JPG, PNG, WEBP hoặc PDF có định dạng hợp lệ.');return file}
