import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import ts from 'typescript';
// Absolute network block: provider mocks use only injected transports.
globalThis.fetch=async()=>{throw Error('NETWORK_DISABLED_IN_TESTS')};
const root=process.cwd(),temp=path.join(root,'.backend-tests');fs.rmSync(temp,{recursive:true,force:true});fs.mkdirSync(temp,{recursive:true});
const files=['lib/product-label.ts','lib/server/product-recognition.ts','lib/server/product-guidance.ts','lib/manual-lookup.ts','lib/server/retire-guides.ts','lib/sorting-rules.ts','lib/server/sorting.ts','lib/server/database.ts','lib/server/auth.ts','lib/server/security.ts','lib/server/quota-sql.ts','lib/server/quota.ts','lib/server/ai-policy.ts','lib/server/ai-provider.ts','lib/server/recognition.ts','app/api/ecosnap/[...path]/route.ts'];
for(const f of files){let code=ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;code=code.replace(/from ['"]cloudflare:workers['"]/g,`from '${path.join(temp,'runtime.mjs')}'`).replace(/from ['"]@supabase\/ssr['"]/g,`from '${path.join(temp,'auth-provider.mjs')}'`).replace(/from ['"](\.[^'"]+)['"]/g,(_,p)=>`from '${p}.js'`);const out=path.join(temp,f.replace(/\.ts$/,'.js'));fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,code)}
fs.writeFileSync(path.join(temp,'runtime.mjs'),'export const env=globalThis.__ecoTestEnv;');
fs.writeFileSync(path.join(temp,'auth-provider.mjs'),`export const parseCookieHeader=s=>s.split(';').filter(Boolean).map(x=>{const [name,value]=x.trim().split('=');return {name,value}});export const serializeCookieHeader=(n,v)=>n+'='+v;export function createServerClient(url,key,opts){return {auth:{getUser:async()=>{const id=opts.cookies.getAll().find(c=>c.name==='session')?.value;const u=globalThis.__ecoTestUsers[id];return {data:{user:u||null},error:u?null:Error('invalid')}},signOut:async()=>({error:null})}}}`);
const sqlitePath=path.join(temp,'data.sqlite');let db=new DatabaseSync(sqlitePath);db.exec('PRAGMA foreign_keys=ON');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+file,'utf8'));
function statement(sql,args=[]){return {bind(...a){return statement(sql,a)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},runSync(){const r=db.prepare(sql).run(...args);return {meta:{changes:r.changes}}},async run(){return this.runSync()}}}
const blobs=new Map();globalThis.__ecoTestEnv={DB:{prepare:sql=>statement(sql),batch:async ss=>{db.exec('BEGIN IMMEDIATE');try{const out=[];for(const s of ss)out.push(s.runSync());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}},BUCKET:{put:async(k,stream,opts)=>blobs.set(k,{bytes:await new Response(stream).arrayBuffer(),opts}),get:async k=>blobs.has(k)?{body:blobs.get(k).bytes}:null,delete:async k=>blobs.delete(k)}};
globalThis.__ecoTestUsers={a:{id:'a',email:'a@example.com',email_confirmed_at:'2026',user_metadata:{}},b:{id:'b',email:'b@example.com',email_confirmed_at:'2026',user_metadata:{}},admin:{id:'admin',email:'owner@example.com',email_confirmed_at:'2026',user_metadata:{}}};
const route=await import(path.join(temp,'app/api/ecosnap/[...path]/route.js'));const q=await import(path.join(temp,'lib/server/quota.js'));const policy=await import(path.join(temp,'lib/server/ai-policy.js'));const {periods}=await import(path.join(temp,'lib/server/database.js'));let passed=0;
async function call(p,{method='GET',user='',body,origin='https://ecosnap.trangphamhp2004.chatgpt.site',ip='1'}={}){return route[method](new Request('https://ecosnap.trangphamhp2004.chatgpt.site/api/ecosnap/'+p,{method,headers:{origin,cookie:user?'session='+user:'','cf-connecting-ip':ip,...(body instanceof FormData?{}:body?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined}))}
async function test(name,fn){await fn();passed++;console.log('PASS',name)}
await test('Missing auth config fails closed; public content remains accessible',async()=>{assert.equal((await call('account')).status,503);assert.equal((await call('content?kind=articles')).status,200)});
globalThis.__ecoTestEnv.SUPABASE_URL='https://fixture.supabase.co';globalThis.__ecoTestEnv.SUPABASE_PUBLISHABLE_KEY='fixture';
await test('Anonymous and forged identities cannot read private data',async()=>{assert.equal((await call('account')).status,401);assert.equal((await call('account',{user:'forged'})).status,401)});
for(const u of ['a','b','admin'])assert.equal((await call('me',{user:u})).status,200);db.prepare("UPDATE users SET role='admin' WHERE id='admin'").run();
await test('Ordinary user cannot access admin or impersonate role in payload',async()=>{assert.equal((await call('admin/overview',{user:'a'})).status,403);assert.equal((await call('admin/settings',{method:'POST',user:'a',body:{role:'admin'}})).status,403)});
await test('Cross-origin mutation rejected',async()=>assert.equal((await call('saved',{method:'POST',user:'a',origin:'https://evil.test',body:{itemId:'x'}})).status,403));
let item;
await test('Admin creates draft, validates publishing and persists content',async()=>{const draft={kind:'items',title:'Vật phẩm kiểm thử',group:'Nhựa',payload:{description:'Test',steps:'Bước kiểm thử'},verified:false,published:false};let r=await call('admin/content',{method:'POST',user:'admin',body:draft});assert.equal(r.status,200);item=(await r.json()).id;assert.equal((await (await call('content?kind=items',{user:'a'})).json()).rows.length,0);assert.equal((await call('admin/content',{method:'POST',user:'admin',body:{...draft,id:item,version:1,published:true}})).status,400);assert.equal((await call('admin/content',{method:'POST',user:'admin',body:{...draft,id:item,version:1,published:true,verified:true,source:'Test fixture only'}})).status,200);assert.equal((await (await call('content?kind=items',{user:'a'})).json()).rows.length,1)});
await test('History ownership, saved uniqueness and durable reload',async()=>{await call('history',{method:'POST',user:'a',body:{itemId:item,userId:'b'}});for(let i=0;i<2;i++)assert.equal((await call('saved',{method:'POST',user:'a',body:{itemId:item,userId:'b'}})).status,200);let a=await (await call('account',{user:'a'})).json(),b=await (await call('account',{user:'b'})).json();assert.equal(a.history.length,1);assert.equal(a.saved.length,1);assert.equal(b.history.length,0);assert.equal(b.saved.length,0);db.close();db=new DatabaseSync(sqlitePath);db.exec('PRAGMA foreign_keys=ON');a=await (await call('account',{user:'a'})).json();assert.equal(a.saved.length,1);await call('saved',{method:'DELETE',user:'b',body:{itemId:item,userId:'a'}});assert.equal((await (await call('account',{user:'a'})).json()).saved.length,1)});
await test('Public AI outcome/cost mutation is unavailable',async()=>{assert.equal((await call('recognize',{method:'POST',user:'a',body:{costVnd:0,status:'success'}})).status,503);assert.equal((await call('settle',{method:'POST',user:'a',body:{status:'success'}})).status,404)});
function form(key,withFile=true){const f=new FormData();for(const [k,v]of Object.entries({name:'Test',email:'test'+key+'@example.com',subject:'Câu hỏi chung',message:'Test feedback',requestKey:key}))f.set(k,v);if(withFile)f.set('file',new File(['%PDF-1.4\nfixture'],'fixture.pdf',{type:'application/pdf'}));return f}
let feedbackId;
await test('Feedback persists, duplicate submission is idempotent, attachments admin-only',async()=>{const key='feedback-test-key-0001';const f=form(key);assert.equal((await call('feedback',{method:'POST',body:f})).status,200);assert.equal((await call('feedback',{method:'POST',body:form(key)})).status,200);const rows=await (await call('admin/feedback',{user:'admin'})).json();assert.equal(rows.rows.length,1);feedbackId=rows.rows[0].id;assert.equal((await call('admin/file/'+feedbackId,{user:'a'})).status,403);const r=await call('admin/file/'+feedbackId,{user:'admin'});assert.equal(r.status,200);assert.match(r.headers.get('Content-Disposition'),/attachment/);assert.equal(await r.text(),'%PDF-1.4\nfixture')});
await test('MIME spoof and oversized attachment rejected',async()=>{let f=form('bad-file-key-00001',false);f.set('file',new File(['<script>x</script>'],'fake.png',{type:'image/png'}));assert.equal((await call('feedback',{method:'POST',body:f,ip:'2'})).status,400);f=form('large-file-key-0001',false);f.set('file',new File([new Uint8Array(5*1024*1024+1)],'large.pdf',{type:'application/pdf'}));assert.equal((await call('feedback',{method:'POST',body:f,ip:'3'})).status,400)});
await test('Feedback rate limit enforced',async()=>{for(let i=0;i<5;i++)assert.equal((await call('feedback',{method:'POST',ip:'rate',body:form('ratelimit-key-000'+i,false)})).status,200);assert.equal((await call('feedback',{method:'POST',ip:'rate',body:form('ratelimit-key-0099',false)})).status,429)});
const usage={costVnd:34,model:'fixture',inputTokens:2,outputTokens:1};const base=Date.parse('2026-10-03T05:00:00Z');
function clear(){db.exec('DELETE FROM ai_requests; DELETE FROM grants; UPDATE users SET failures=0,cooldown_until=0; UPDATE settings SET daily_limit=5,monthly_limit=20,budget_vnd=5000000,reserve_vnd=1000;')}
await q.getSettings();
await test('Multiple tabs allow one pending request per user; duplicate key reused',async()=>{clear();const r=await Promise.allSettled(Array.from({length:20},(_,i)=>q.reserve('a','parallel-key-'+String(i).padStart(6,'0'),base)));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const first=r.find(x=>x.status==='fulfilled').value;const dup=await q.reserve('a','parallel-key-000000',base);assert.equal(dup.id,first.id);assert.equal(dup.reused,true)});
await test('Unknown/errors refund quota; three unknowns cause cooldown; settlement idempotent',async()=>{clear();for(let i=0;i<3;i++){const r=await q.reserve('a','unknown-key-00000'+i,base);await q.settle(r.id,'unknown',usage,base);await q.settle(r.id,'unknown',usage,base)}const state=await q.quota('a',base);assert.equal(state.dayUsed,0);assert.equal(state.monthUsed,0);assert.equal(state.cooldownUntil,base+600000);await assert.rejects(()=>q.reserve('a','cooldown-key-0001',base+100));const r=await q.reserve('a','cooldown-key-0002',base+600001);await q.settle(r.id,'error',usage,base+600001);assert.equal((await q.quota('a',base+600001)).dayUsed,0);assert.equal(db.prepare('SELECT SUM(cost_vnd) n FROM ai_requests').get().n,136)});
await test('Hard monthly limit, Vietnam midnight reset and grants cannot bypass cap',async()=>{clear();for(let d=0;d<4;d++)for(let i=0;i<5;i++){const r=await q.reserve('a',`monthly-key-${d}-000${i}`,base+d*86400000);await q.settle(r.id,'success',usage,base+d*86400000)}await assert.rejects(()=>q.reserve('a','monthly-block-001',base+4*86400000));db.prepare('INSERT INTO grants VALUES(?,?,?,?,?,?,?)').run('g','a','2026-10',2,'admin','test',base);await assert.rejects(()=>q.reserve('a','monthly-grant-001',base+4*86400000));assert.equal((await q.quota('a',Date.parse('2026-10-31T17:00:00Z'))).bonus,0);assert.equal(periods(Date.parse('2026-10-31T16:59:59Z')).month,'2026-10');assert.equal(periods(Date.parse('2026-10-31T17:00:00Z')).month,'2026-11');assert.equal((await q.quota('a',Date.parse('2026-10-31T17:00:00Z'))).monthUsed,0)});
await test('Global budget accounts for pending reservations and unknown costs across users',async()=>{clear();db.prepare("UPDATE settings SET budget_vnd=? WHERE id='main'").run(policy.MIN_RESERVE_VND+500);const r=await q.reserve('a','budget-user-a-001',base);await assert.rejects(()=>q.reserve('b','budget-user-b-001',base));await q.settle(r.id,'unknown',{...usage,costVnd:600},base);await assert.rejects(()=>q.reserve('b','budget-user-b-002',base));assert.equal((await q.quota('b',base)).dayUsed,0)});
await test('Optimistic content update rejects stale version',async()=>assert.equal((await call('admin/content',{method:'POST',user:'admin',body:{id:item,kind:'items',title:'Stale',version:1,payload:{},published:false,verified:false}})).status,409));
await (await import('./recognition-cases.mjs')).run({assert,test,call,db,statement,q,policy,temp,base,clear,blobs});
await (await import('./trial-cases.mjs')).run({assert,test,call,db,q,policy,temp,base,clear});
await (await import('./sorting-cases.mjs')).run({assert,test,call,db,q,policy,temp,base,clear});
await (await import('./product-cases.mjs')).run({assert,test,call,db,q,policy,temp,base,clear,blobs});
console.log(`${passed} backend checks passed. Auth provider is a TEST FIXTURE; no real Google/email or cloud storage integration tested.`);if(process.env.ECOSNAP_UI_TEST==='1')await (await import('./ui-fixture.mjs')).start({temp,call,clear,db,base,policy});db.close();fs.rmSync(temp,{recursive:true,force:true});
