import path from 'node:path';
export async function run({assert,test,call,db,q,policy,temp,base,clear}){
 const rules=await import(path.join(temp,'lib/sorting-rules.js')),manual=await import(path.join(temp,'lib/manual-lookup.js')),sorting=await import(path.join(temp,'lib/server/sorting.js')),ai=await import(path.join(temp,'lib/server/recognition.js')),provider=await import(path.join(temp,'lib/server/ai-provider.js'));
 const post=(body,user='a')=>call('sorting',{method:'POST',user,body});let sequence=0;
 const body=(ids,extra={})=>({ids,version:rules.SORTING_VERSION,key:'sort-fixture-'+String(++sequence).padStart(8,'0'),confirmed:true,...extra});
 await test('Three national groups; tissue, coffee and hazardous exceptions are explicit',async()=>{assert.equal(rules.SORTING_GROUPS.length,3);assert.equal(rules.sortingPlan(['tissue']).components[0].group,'other');assert.equal(rules.sortingPlan(['garden']).components[0].group,'other');assert.equal(rules.sortingPlan(['battery']).components[0].special,true);assert.equal(rules.sortingPlan(['dirty-paper','laminated']).complete,false)});
 await test('Natural manual phrases lead to condition questions without AI or exact sentence records',async()=>{
  for(const text of ['hộp bánh gato còn nguyên vỏ dính chất bẩn','hop banh gato con banh','hộp bánh kem'])assert.equal(manual.interpretManual(text).kind,'cake');
  assert.equal(manual.interpretManual('khăn giấy dính đồ ăn').kind,'tissue');assert.equal(manual.interpretManual('chai nước còn nguyên').kind,'bottle');assert.equal(manual.interpretManual('chai nước còn nguyên').answers.intent,undefined);
  assert.deepEqual(manual.resolveManual('cake',{food:'yes',wrapper:'dirty-paper',base:'laminated'}).ids,['food','dirty-paper','laminated']);
  assert.deepEqual(manual.resolveManual('tissue',{used:'yes',food:'yes'}).ids,['tissue','food']);assert.deepEqual(manual.resolveManual('bottle',{intent:'keep'}),{ids:[],keep:true});
 });
 await test('Unknown liquid never permits the bottle shell to be assumed safe recycling',async()=>{const p=rules.sortingPlan(['bottle','unknown-liquid']);assert.equal(p.complete,false);assert.ok(p.components.every(r=>r.group===null));assert.deepEqual(manual.resolveManual('bottle',{intent:'discard',content:'chemical',material:'bottle'}).ids,['hazardous'])});
 await test('Manual sorting, review and saving are server-owned and use no AI quota or cost',async()=>{clear();const r=await post(body(['foam','food'],{group:'recycle',costVnd:0,userId:'b'}));assert.equal(r.status,200);const result=await r.json();assert.deepEqual(result.plan.components.map(x=>x.group).sort(),['food','other']);assert.equal((await call('sorting?id='+result.id,{user:'b'})).status,404);for(let n=0;n<3;n++)assert.equal((await call('sorting?id='+result.id,{user:'a'})).status,200);assert.equal((await call('sorting/saved',{method:'POST',user:'a',body:{id:result.id,saved:true}})).status,200);assert.equal((await call('sorting/saved',{method:'POST',user:'b',body:{id:result.id,saved:false}})).status,404);const account=await (await call('account',{user:'a'})).json();assert.ok(account.sorting.some(x=>x.id===result.id&&x.saved));assert.equal(db.prepare('SELECT COUNT(*) n FROM ai_requests').get().n,0);assert.equal((await q.quota('a',base)).dayUsed,0)});
 await test('Manual submission rejects unknown rules, forged versions, missing confirmation and anonymous users',async()=>{assert.equal((await post(body(['made-up']))).status,400);assert.equal((await post(body(['food'],{version:999}))).status,409);assert.equal((await post(body(['food'],{confirmed:false}))).status,400);assert.equal((await post(body(['food']),'')).status,401)});
 await test('Concurrent manual confirmation writes one record; conflicting duplicate cannot change it',async()=>{const b=body(['foam','food']);const rs=await Promise.all(Array.from({length:8},()=>post(b)));for(const r of rs)assert.equal(r.status,200);const results=await Promise.all(rs.map(r=>r.json()));assert.equal(new Set(results.map(r=>r.id)).size,1);assert.equal((await post({...b,ids:['battery']})).status,409)});
 await (await import('./manual-object-cases.mjs')).run({assert,test,call,db,q,base,clear,manual,rules,post,body});
 const jpeg=new Uint8Array([255,216,255,192,0,11,8,0,1,0,1,1,1,17,0,255,218,0,8,1,1,0,0,63,0,1,255,217]);let calls=0,payload;
 const scene={identified:true,components:[{name:'Hộp xốp',rule_id:'foam',confidence:.98},{name:'Thức ăn thừa',rule_id:'food',confidence:.97}]};
 const request=(key)=>{const f=new FormData();f.set('image',new File([jpeg],'fixture.jpg',{type:'image/jpeg'}));f.set('requestKey',key);f.set('consent','openai');return new Request('https://ecosnap.trangphamhp2004.chatgpt.site/api/ecosnap/recognize',{method:'POST',body:f})};
 const mock=v=>provider.sortingAIProvider('FAKE_SORTING_KEY',async(url,opts)=>{calls++;payload=JSON.parse(opts.body);return Response.json({id:'sorting_fixture',model:policy.AI_MODEL,status:'completed',usage:{input_tokens:1000,output_tokens:180},output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(v)}]}]})});
 await test('Mocked multi-part recognition counts one success and returns no AI-authored advice',async()=>{clear();calls=0;const r=await ai.runRecognition(request('sorting-ai-fixture-0001'),'a',mock(scene),()=>base,false,'sorting');assert.equal(r.status,'success');assert.equal(r.schemaVersion,2);assert.equal(r.components.length,2);assert.equal(r.quota.dayUsed,1);assert.equal(calls,1);assert.equal(payload.store,false);assert.equal(payload.text.format.schema.properties.components.maxItems,6);assert.equal(r.components[0].steps,undefined);const saved=await post(body(['foam','food'],{recognitionId:r.requestId}));assert.equal(saved.status,200);assert.equal((await post(body(['foam','food'],{recognitionId:r.requestId}),'b')).status,409);assert.equal((await q.quota('a',base)).dayUsed,1);assert.equal(calls,1)});
 await test('Duplicate keys cannot switch photos or collide with another confirmed photo result',async()=>{
  clear();const a=await ai.runRecognition(request('sorting-association-photo-01'),'a',mock(scene),()=>base,false,'sorting');const b=await ai.runRecognition(request('sorting-association-photo-02'),'a',mock(scene),()=>base,false,'sorting');
  const ba=body(['foam','food'],{recognitionId:a.requestId}),bb=body(['foam','food'],{recognitionId:b.requestId});
  assert.equal((await post(ba)).status,200);assert.equal((await post({...ba,recognitionId:b.requestId})).status,409);
  assert.equal((await post(bb)).status,200);assert.equal((await post({...ba,recognitionId:b.requestId})).status,409);assert.equal((await post({...ba,recognitionId:undefined})).status,409);
  assert.equal((await post(body(['foam','food'],{recognitionId:a.requestId}))).status,200);
 });
 await test('Mixed unknown or unsupported parts stay unresolved and do not consume user turns',async()=>{clear();const variants=[{...scene,components:[scene.components[0],{name:'Không rõ',rule_id:null,confidence:.2}]},{...scene,components:[{name:'Giấy dính dầu',rule_id:'dirty-paper',confidence:.99}]},{...scene,components:[{name:'Sai mã',rule_id:'invented',confidence:.99}]}];for(let i=0;i<variants.length;i++){const r=await ai.runRecognition(request('sorting-unknown-fixture-'+i),'a',mock(variants[i]),()=>base,false,'sorting');assert.notEqual(r.status,'success');assert.equal(r.quota.dayUsed,0)}assert.equal(db.prepare('SELECT COUNT(*) n FROM ai_requests').get().n,3);assert.ok(db.prepare('SELECT SUM(cost_vnd) c FROM ai_requests').get().c>0)});
 await test('Scene validation rejects provider instructions, malformed parts and excess parts',async()=>{assert.equal(sorting.validScene({...scene,instructions:'evil'}),false);assert.equal(sorting.validScene({identified:true,components:[{name:'x',rule_id:'food',confidence:NaN}]}),false);assert.equal(sorting.validScene({identified:true,components:Array(7).fill(scene.components[0])}),false)});
 await test('Both paid gates stay closed after the new flow; browser flags cannot enable AI',async()=>{assert.equal(policy.LIVE_OPENAI_ENABLED,false);assert.equal(policy.ADMIN_TRIAL_ENABLED,false);assert.equal((await call('recognize',{method:'POST',user:'admin',body:{enable:true,mode:'sorting',mock:true}})).status,503)});
 await test('Legacy knowledge cleanup is admin-only, limited to exact versions and preserves financial/account data',async()=>{
  const id='group-0';db.prepare("UPDATE content SET version=2 WHERE id=?").run(id);
  assert.equal((await call('admin/legacy-guides',{method:'POST',user:'a',body:{confirmed:true}})).status,403);
  assert.equal((await call('admin/legacy-guides',{method:'POST',user:'admin',body:{confirmed:true}})).status,409);
  assert.ok(db.prepare('SELECT id FROM content WHERE id=?').get(id));db.prepare('UPDATE content SET version=1 WHERE id=?').run(id);
  const before={users:db.prepare('SELECT COUNT(*) n FROM users').get().n,requests:db.prepare('SELECT COUNT(*) n FROM ai_requests').get().n,settings:db.prepare('SELECT * FROM settings').all()};
  const r=await call('admin/legacy-guides',{method:'POST',user:'admin',body:{confirmed:true}});assert.equal(r.status,200);assert.equal((await r.json()).removed,8);assert.equal(db.prepare('SELECT id FROM content WHERE id=?').get(id),undefined);assert.ok(db.prepare("SELECT id FROM content WHERE id='ai-glass'").get());assert.equal(db.prepare('SELECT COUNT(*) n FROM users').get().n,before.users);assert.equal(db.prepare('SELECT COUNT(*) n FROM ai_requests').get().n,before.requests);assert.deepEqual(db.prepare('SELECT * FROM settings').all(),before.settings);assert.equal((await (await call('admin/legacy-guides',{method:'POST',user:'admin',body:{confirmed:true}})).json()).removed,0);
 });
}
