// Local-only browser fixtures; no production data, credentials or OpenAI requests.
// Pass the installed Playwright module URL; do not install or bundle it in the Site.
import {strict as assert} from 'node:assert';import fs from 'node:fs';
const {chromium}=await import(process.argv[2]||'playwright');
const browser=await chromium.launch({headless:true,...(process.argv[3]?{executablePath:process.argv[3]}:{})});const context=await browser.newContext({viewport:{width:1280,height:900}});
let mode='disabled',lost=false,recognizeCalls=0,confirmBody=null;
const item={id:'glass',name:'Chai thủy tinh',title:'Chai thủy tinh',group:'Thủy tinh',description:'Vật phẩm giả lập cho kiểm thử',steps:'Hướng dẫn đã kiểm duyệt trong dữ liệu kiểm thử.',source:'Fixture kiểm thử',verified:true,published:true,version:1};
const second={...item,id:'paper',name:'Hộp giấy',title:'Hộp giấy',group:'Giấy'};
const quota=()=>({dayUsed:mode==='exhausted'?5:0,dayPending:mode==='lost'?1:0,monthUsed:0,monthPending:mode==='lost'?1:0,dayLimit:5,monthLimit:20,bonus:0,cooldownUntil:0,budgetAvailable:true,processing:mode==='lost',aiEnabled:mode!=='disabled'});
const success=()=>({status:'success',requestId:'fixture-request',message:'Gợi ý giả lập để kiểm thử.',identification:{name:item.name,group:item.group},candidate:item,quota:{...quota(),dayUsed:1,monthUsed:1,processing:false,dayPending:0,monthPending:0}});
await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!=='http://127.0.0.1:5173'){await route.abort();return}if(!url.pathname.startsWith('/api/ecosnap/'))return route.continue();const p=url.pathname.slice('/api/ecosnap/'.length);let body={};
 if(p==='me')body={user:{id:'fixture',email:'fixture@example.test',role:'user'},authConfigured:true,quota:quota()};
 else if(p==='content')body={rows:url.searchParams.get('kind')==='items'?[item,second]:[]};
 else if(p==='account')body={saved:[],history:[],quota:quota()};
 else if(p==='recognize'){recognizeCalls++;if(mode==='lost'&&!lost){lost=true;return route.abort('failed')}body=mode==='unknown'?{status:'unknown',requestId:'fixture-request',message:'Chưa xác định. Không trừ lượt.',quota:quota()}:mode==='missing'?{status:'no_guidance',requestId:'fixture-request',message:'Chưa có hướng dẫn phù hợp.',identification:{name:'Đồ vật chưa có trong kho',group:'Khác'},candidate:null,quota:quota()}:success();}
 else if(p==='recognition')body=success();
 else if(p==='recognition/confirm'){confirmBody=route.request().postDataJSON();body={itemId:confirmBody.itemId};}
 return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/#/scan');await page.getByRole('heading',{name:'Thêm ảnh vật phẩm'}).waitFor();
const buffer=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=300;const ctx=c.getContext('2d');ctx.fillStyle='#ddd';ctx.fillRect(0,0,400,300);return c.toDataURL('image/png').split(',')[1]}),'base64');
async function upload(){await page.locator('input[type=file]').setInputFiles({name:'test-fixture.png',mimeType:'image/png',buffer});await page.getByAltText('Ảnh vật phẩm bạn chọn').waitFor();await page.getByRole('checkbox').check();}
await upload();assert.equal(await page.getByRole('button',{name:'AI đang tắt, chờ duyệt thử nghiệm',exact:true}).isDisabled(),true);assert.equal(recognizeCalls,0);console.log('PASS Disabled production-like UI permits image preview but sends no recognition');
mode='success';await page.reload();await page.getByRole('heading',{name:'Thêm ảnh vật phẩm'}).waitFor();await upload();await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).click();await page.getByRole('heading',{name:'Xác nhận vật phẩm'}).waitFor();await page.getByRole('button',{name:'Không đúng, chọn lại vật phẩm'}).click();await page.getByLabel('Vật phẩm bạn xác nhận').selectOption('paper');await page.getByRole('button',{name:'Xác nhận và xem hướng dẫn'}).click();await page.getByRole('heading',{name:'Hộp giấy',exact:true}).waitFor();assert.equal(confirmBody.version,1);assert.equal(confirmBody.itemId,'paper');console.log('PASS Mock success -> corrected material -> explicit confirmation -> reviewed guide');
mode='missing';await page.goto('http://127.0.0.1:5173/#/scan');await upload();await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).click();await page.getByRole('heading',{name:'Chưa có hướng dẫn phù hợp'}).waitFor();assert.equal(await page.getByRole('button',{name:'Xác nhận và xem hướng dẫn'}).isDisabled(),true);console.log('PASS Missing guidance does not preselect an unrelated catalog item');
mode='unknown';await page.reload();await page.getByRole('heading',{name:'Thêm ảnh vật phẩm'}).waitFor();await upload();await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).click();await page.getByRole('heading',{name:'Chưa xác định được'}).waitFor();console.log('PASS Unknown result offers free manual lookup');
mode='success';await page.reload();await page.getByRole('heading',{name:'Thêm ảnh vật phẩm'}).waitFor();await upload();mode='lost';await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).click();await page.getByRole('button',{name:'Lấy lại kết quả · không gửi ảnh lần nữa'}).waitFor();const before=recognizeCalls;await page.getByRole('button',{name:'Lấy lại kết quả · không gửi ảnh lần nữa'}).click();await page.getByRole('heading',{name:'Xác nhận vật phẩm'}).waitFor();assert.equal(recognizeCalls,before);console.log('PASS Lost POST response recovers by key without resending image or provider request');
mode='exhausted';await page.reload();await page.getByRole('heading',{name:'Thêm ảnh vật phẩm'}).waitFor();await upload();assert.equal(await page.getByRole('button',{name:'Đã hết lượt hôm nay',exact:true}).isDisabled(),true);mode='success';await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).isEnabled(),true);console.log('PASS Quota reset/other-tab completion refreshes on focus');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Nhận diện ảnh',exact:true}).click();await page.getByRole('heading',{name:'Xác nhận vật phẩm'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);fs.mkdirSync('work/ui-tests',{recursive:true});await page.screenshot({path:'work/ui-tests/mobile-fixture.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'work/ui-tests/desktop-fixture.png',fullPage:true});console.log('PASS Mobile/desktop scan flow has no horizontal overflow');assert.deepEqual(errors,[]);console.log('7 browser checks passed. All account/content/recognition responses are LOCAL FIXTURES; external requests blocked.');await browser.close();
