'use client';
import React,{useEffect,useState} from 'react';
import {BookOpen,MapPin,Search} from 'lucide-react';
import {filterPoints,knowledgeExpired,KNOWLEDGE_REVISION,sourceLinks} from '../lib/knowledge';
export function Sources({source,checkedAt}:{source:string;checkedAt?:string}){const links=sourceLinks(source);return <div className="knowledge-sources">{checkedAt&&<p>Đối chiếu nguồn: {checkedAt}.</p>}{links.length>0&&<details><summary>Nguồn tham khảo</summary><ul>{links.map((s,i)=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.label}{links.filter(l=>l.label===s.label).length>1?' · nguồn '+(i+1):''}</a></li>)}</ul></details>}</div>}
export function ArticleBody({body}:{body:string}){return <div className="knowledge-body">{body.split(/\n\n+/).filter(Boolean).map((s,i)=>s.startsWith('## ')?<h2 key={i}>{s.slice(3)}</h2>:<p key={i}>{s}</p>)}</div>}
export function RelatedReading({rows}:{rows:any[]}){return rows?.length?<div className="related-reading"><h3>Bài viết phù hợp với các phần của bạn</h3>{rows.map(r=><a className="related-link" href={'#/article/'+encodeURIComponent(r.id)} onClick={()=>window.scrollTo(0,0)} key={r.id}><BookOpen size={20}/><span><strong>{r.title}</strong>{r.summary&&<small>{r.summary}</small>}</span></a>)}</div>:null}
export function KnowledgeImport({onDone}:{onDone:()=>Promise<void>}){
 const [status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function request(method='GET'){const r=await fetch('/api/ecosnap/admin/knowledge-pack',{method,credentials:'same-origin',...(method==='POST'?{headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:KNOWLEDGE_REVISION})}:{})});const data:any=await r.json();if(!r.ok)throw Error(data.error||'Chưa cập nhật được kho nội dung.');return data}
 useEffect(()=>{request().then(setStatus).catch(e=>setError(e.message))},[]);
 if(!status&&!error)return null;
 return <div className="card knowledge-import"><h3>Kho kiến thức EcoSnap · 03/10/2026</h3><p>{status?`${status.installed}/${status.total} bài viết, điểm thu gom và dự án đã có trong cơ sở dữ liệu.`:error}</p>{!!status?.remaining&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{let next=status;while(next.remaining){next=await request('POST');setStatus(next)}await onDone()}catch(e){setError(e instanceof Error?e.message:'Chưa cập nhật được.')}finally{setBusy(false)}}}>{busy?'Đang cập nhật kho nội dung…':'Bổ sung kho kiến thức đã đối chiếu nguồn'}</button>}{error&&status&&<p role="alert">{error}</p>}</div>
}
export function PointDirectory({points}:{points:any[]}){
 const [query,setQuery]=useState(''),[area,setArea]=useState(''),[program,setProgram]=useState(''),[limit,setLimit]=useState(18);
 const list=filterPoints(points,query,area,program),programs=[...new Set(points.map(p=>p.program).filter(Boolean))].sort();
 return <section className="section knowledge-directory"><div className="page-title"><div className="eyebrow">Điểm thu gom</div><h1>Mang đúng đồ, đến đúng nơi.</h1><p>Các điểm và chương trình tại Hà Nội có nguồn công khai để bạn kiểm tra trước khi đi.</p></div><div className="notice">Danh sách đang được bổ sung, chưa bao quát mọi địa điểm. “Đơn vị công bố” nghĩa là thông tin có trên nguồn của chương trình; EcoSnap chưa gọi xác nhận từng điểm. Một số nơi cần đăng ký hoặc chỉ nhận vào ngày nhất định.</div><div className="knowledge-filters"><label>Tìm vật phẩm hoặc địa chỉ<div className="search"><Search size={20}/><input value={query} placeholder="Hộp sữa, pin, quần áo…" onChange={e=>{setQuery(e.target.value);setLimit(18)}}/></div></label><label>Khu vực<input value={area} placeholder="Ví dụ: Hà Đông" onChange={e=>{setArea(e.target.value);setLimit(18)}}/></label><label>Chương trình<select aria-label="Chương trình" value={program} onChange={e=>{setProgram(e.target.value);setLimit(18)}}><option value="">Tất cả chương trình</option>{programs.map(p=><option key={p}>{p}</option>)}</select></label></div><p role="status">{list.length} điểm phù hợp · Địa chỉ giữ theo nguồn công bố, tên khu vực có thể là tên cũ.</p><div className="grid three">{list.slice(0,limit).map(p=><article className="card collection-point" key={p.id}><span className="icon"><MapPin/></span><small className="knowledge-program">{p.program}</small><h2>{p.name||p.title}</h2><span className="knowledge-status">{knowledgeExpired(p)?'Hết thời gian công bố · cần xác nhận lại':p.status||'Cần xác nhận'}</span><p><strong>Nhận:</strong> {p.materials}</p><p><strong>Địa chỉ:</strong> {p.address}</p><p><strong>Lịch nhận:</strong> {p.hours||'Hỏi nơi tiếp nhận trước khi đi.'}</p>{p.validUntil&&<p><strong>Đợt công bố đến:</strong> {p.validUntil}</p>}{p.conditions&&<p className="point-conditions">{p.conditions}</p>}{p.phone&&<p><strong>Liên hệ:</strong> {p.phone}</p>}<Sources source={p.source} checkedAt={p.checkedAt}/><div className="actions"><a className="text" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.address+(/Hà Nội/i.test(p.address)?'':' Hà Nội'))} target="_blank" rel="noopener noreferrer">Tìm địa chỉ trên bản đồ</a></div></article>)}</div>{!list.length&&<div className="empty card">Chưa tìm thấy điểm phù hợp. Thử tên vật phẩm khác hoặc chọn tất cả chương trình.</div>}{limit<list.length&&<button className="secondary center" onClick={()=>setLimit(limit+18)}>Xem thêm địa điểm</button>}</section>
}
