'use client';
import React,{useState} from 'react';
import {EMPTY_PRODUCT,MATERIAL_CODES,PACKAGE_FORMS,packageNames,type ProductContext} from '../lib/product-label';
import {SortingPicker} from './sorting-flow';
export function ProductFields({value,onChange,disabled=false}:{value:ProductContext;onChange:(v:ProductContext)=>void;disabled?:boolean}){
 const set=(key:keyof ProductContext,v:string)=>onChange({...value,[key]:v});
 return <div className="form product-fields"><label>Thương hiệu<input maxLength={100} disabled={disabled} value={value.brand} placeholder="Chưa đọc rõ / không có nhãn" onChange={e=>set('brand',e.target.value)}/></label><label>Tên sản phẩm<input maxLength={100} disabled={disabled} value={value.productName} placeholder="Tên trên nhãn, có thể để trống" onChange={e=>set('productName',e.target.value)}/></label><label>Dung tích / phiên bản<input maxLength={100} disabled={disabled} value={value.variant} placeholder="Ví dụ: 500 ml" onChange={e=>set('variant',e.target.value)}/></label><label>Dạng bao bì<select disabled={disabled} value={value.packageForm} onChange={e=>set('packageForm',e.target.value)}>{PACKAGE_FORMS.map(v=><option key={v} value={v}>{packageNames[v]}</option>)}</select></label><label>Mã vật liệu trên thân bao bì<select disabled={disabled} value={value.materialCode} onChange={e=>set('materialCode',e.target.value)}>{MATERIAL_CODES.map(v=><option key={v} value={v}>{v==='unknown'?'Chưa đọc rõ / không có mã':v}</option>)}</select><small>Không dùng mã trên nắp cho thân chai. Mã vật liệu chưa đảm bảo nơi thu gom sẽ nhận.</small></label><label>Còn sản phẩm trong bao bì không?<select disabled={disabled} value={value.remaining} onChange={e=>set('remaining',e.target.value)}><option value="unknown">Chưa rõ / chưa kiểm tra</option><option value="empty">Tôi đã kiểm tra, bao bì đã rỗng</option><option value="remains">Còn sản phẩm bên trong</option></select></label><label>Nhãn có cảnh báo nguy hại không?<select disabled={disabled} value={value.warning} onChange={e=>set('warning',e.target.value)}><option value="unknown">Chưa kiểm tra / chưa đọc rõ</option><option value="present">Có biểu tượng hoặc cảnh báo nguy hại</option><option value="none">Đã kiểm tra nhãn, không thấy cảnh báo nguy hại</option></select></label></div>;
}
export function ProductConfirmation({result,onDone,onBusyChange}:{result:any;onDone:(id:string)=>void;onBusyChange?:(v:boolean)=>void}){
 const hasLabel=!!(result.product?.brand||result.product?.productName||result.product?.variant||result.product?.warning==='present');
 const [product,setProduct]=useState<ProductContext>(result.product||EMPTY_PRODUCT),[reviewed,setReviewed]=useState(!hasLabel),[saving,setSaving]=useState(false);
 return <div className="product-confirmation"><div className="card spaced"><div className="eyebrow">Thông tin bổ sung</div><h2>{hasLabel?'Kiểm tra thông tin trên nhãn':'Không có nhãn vẫn phân loại được'}</h2><p>{hasLabel?`AI đọc thông tin từ ảnh${result.labelPhoto?` số ${result.labelPhoto}`:''}. Sửa chỗ chưa đúng; có thể để trống tên và thương hiệu.`:'Bạn có thể xác nhận các phần bên dưới như khi tra cứu thủ công. Thương hiệu và mã nhựa chưa rõ được để trống.'}</p><details open={hasLabel||undefined}><summary>Nhãn, bao bì và phần còn bên trong (nếu có)</summary><ProductFields disabled={saving} value={product} onChange={v=>{setProduct(v);setReviewed(false)}}/>{result.readings?.length>0&&<details><summary>Mã đọc được ở từng phần</summary>{result.readings.map((r:any,i:number)=><p key={i}>{r.name} · Ảnh {r.photo} · {r.materialCode==='unknown'?'Chưa đọc rõ mã':r.materialCode}</p>)}</details>}</details>{product.warning==='present'&&<p className="warning">Có dấu hiệu nguy hại. Kiểm tra phần chất thải nguy hại trong danh mục; chưa làm sạch hoặc bỏ chung theo chất liệu vỏ.</p>}{(!reviewed||hasLabel)&&<label className="checkbox"><input type="checkbox" disabled={saving} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Tôi đã kiểm tra thông tin, sửa chỗ sai và giữ “Chưa rõ” ở phần chưa biết.</label>}</div>{reviewed&&<SortingPicker compact key={JSON.stringify(product)} onSavingChange={v=>{setSaving(v);onBusyChange?.(v)}} product={product} observations={result.components} recognitionId={result.requestId} onDone={onDone}/>}</div>;
}
export function ProductAdvice({product,guidance}:{product:ProductContext;guidance:any}){return <div className="card spaced product-advice"><div className="eyebrow">Thông tin nhãn đã xác nhận</div><h2>{[product.brand,product.productName,product.variant].filter(Boolean).join(' · ')||'Chưa xác định tên sản phẩm'}</h2><p>{packageNames[product.packageForm]} · {product.materialCode==='unknown'?'Chưa rõ mã vật liệu':product.materialCode}</p><p>{guidance.message}</p>{guidance.references.map((r:any)=><div className="product-reference" key={r.title}><h3>{r.title}</h3><p>{r.body}</p><a href={r.source} target="_blank" rel="noreferrer">Nguồn chính thức · đối chiếu {guidance.checkedAt}</a></div>)}{guidance.programs.map((p:any)=><div className="product-reference" key={p.title}><h3>{p.title}</h3><p>{p.scope}</p><ul>{p.steps.map((s:string)=><li key={s}>{s}</li>)}</ul><a href={p.source} target="_blank" rel="noreferrer">Xem điều kiện tại hãng · đối chiếu {p.checkedAt}</a></div>)}</div>}
