'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Search,Check,Plus,X,Recycle,Leaf,Package,Bookmark,AlertTriangle} from 'lucide-react';
import {RelatedReading} from './knowledge';
import {MaterialKnowledge} from './material-knowledge';
import {ProductAdvice} from './product-label';
import {productSelections,type ProductContext} from '../lib/product-label';
import {SORTING_GROUPS,normalizeSearch,type SortingRule} from '../lib/sorting-rules';
type Catalog={version:number;rules:SortingRule[];presets:{name:string;ids:string[]}[];source:string};
type Observation={name:string;rule_id:string|null;confidence:number};
export async function sortingRequest(path:string,body?:unknown):Promise<any>{const r=await fetch('/api/ecosnap/'+path,{credentials:'same-origin',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const value:any=await r.json();if(!r.ok)throw Error(value.error||'Chưa tải được hướng dẫn.');return value;}
export function ThreeGroups(){return <div className="grid three sorting-groups">{SORTING_GROUPS.map((g,i)=>{const Icon=[Recycle,Leaf,Package][i];return <div key={g.id} className={'card sorting-group bin-'+g.id}><Icon size={30}/><h3>{g.name}</h3><p>{g.description}</p></div>})}</div>}
export function LegacyGuideReset({onDone}:{onDone:()=>Promise<void>}){const [count,setCount]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{sortingRequest('admin/legacy-guides').then(r=>setCount(r.count)).catch(()=>{})},[]);if(!count)return null;return <div className="card spaced"><h3>Thay kho hướng dẫn cũ</h3><p>{count} mục cũ sẽ được xoá để dùng bộ phân loại mới. Tài khoản, cấu hình và sổ chi phí được giữ nguyên.</p><button disabled={busy} className="secondary" onClick={async()=>{setBusy(true);try{await sortingRequest('admin/legacy-guides',{confirmed:true});setCount(0);await onDone()}catch(e){setError(e instanceof Error?e.message:'Chưa xoá được.')}finally{setBusy(false)}}}>Xoá kho hướng dẫn cũ</button>{error&&<p role="alert">{error}</p>}</div>}
export function SortingPicker({observations,recognitionId,product,initialGroup='',initialIds=[],initialQuery='',compact=false,onDone,onSavingChange}:{observations?:Observation[];recognitionId?:string;product?:ProductContext;initialGroup?:string;initialIds?:string[];initialQuery?:string;compact?:boolean;onDone:(id:string)=>void;onSavingChange?:(busy:boolean)=>void}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(initialQuery),[group,setGroup]=useState(initialGroup),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(!compact);const key=useRef(''),lock=useRef(false);
 useEffect(()=>{let active=true;sortingRequest('sorting/catalog').then(c=>{if(active){setCatalog(c);setSelected([...new Set([...initialIds,...(observations||[]).map(o=>o.rule_id||'unknown-item')].filter((id):id is string=>!!id&&c.rules.some((r:SortingRule)=>r.id===id)))]);}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[]);
 const change=(ids:string[])=>{setSelected(ids);setConfirmed(false);key.current='';setError('')};
 const toggle=(id:string)=>{if(selected.includes(id))change(selected.filter(x=>x!==id));else if(selected.length<6)change([...selected,id]);else setError('Mỗi lần chọn tối đa 6 phần. Với nhiều rác hơn, hãy chia thành từng tình huống nhỏ.')};
 async function submit(){if(!catalog||!confirmed||lock.current)return;lock.current=true;setBusy(true);onSavingChange?.(true);setError('');if(!key.current)key.current=crypto.randomUUID();try{const r=await sortingRequest('sorting',{ids:selected,version:catalog.version,key:key.current,confirmed:true,...(recognitionId?{recognitionId}:{}),...(product?{product,productReviewed:true}:{})});onDone(r.id)}catch(e){setError(e instanceof Error?e.message:'Chưa lưu được kết quả.')}finally{lock.current=false;setBusy(false);onSavingChange?.(false)}}
 if(!catalog)return <div className="card spaced" role="status">{error||'Đang tải hướng dẫn phân loại…'}{error&&<button className="text" onClick={()=>window.location.reload()}>Tải lại</button>}</div>;
 const displayed=product?productSelections(selected,product):selected;
 const chosen=displayed.map(id=>catalog.rules.find(r=>r.id===id)!).filter(Boolean);
 const words=normalizeSearch(query).split(/[^a-z0-9]+/).filter(w=>w.length>1&&!['cua','toi','con','nguyen','voi','can','bo','vao'].includes(w));
 const matches=catalog.rules.map(r=>({r,score:words.filter(w=>normalizeSearch(r.name+' '+r.keywords).split(/[^a-z0-9]+/).includes(w)).length})).filter(({r,score})=>(!words.length||score>0||r.id==='unknown-item')).sort((a,b)=>b.score-a.score).map(x=>x.r);
 return <div className="sorting-picker">
  {observations&&<div className="card spaced"><h2>Kiểm tra các phần trong ảnh</h2><p>AI gợi ý: {observations.length?observations.map(o=>o.name).join(' · '):'Chưa rõ các phần trong ảnh.'}</p><p>Bạn có thể bỏ phần sai, thêm phần còn thiếu hoặc đổi chất liệu. Một ảnh có nhiều phần vẫn chỉ tính một lượt có kết quả.</p></div>}
  {!observations&&!compact&&<><p className="muted">Tra cứu thủ công miễn lượt. Chọn cả bao bì và thức ăn nếu còn bên trong.</p><div className="scenario-list">{catalog.presets.map(p=><button className="secondary" key={p.name} disabled={busy} onClick={()=>change(p.ids)}>{p.name}</button>)}</div></>}
  {compact&&<button className="text" onClick={()=>setEditing(!editing)}>{editing?'Ẩn danh mục':'Thêm hoặc sửa các phần'}</button>}
  {editing&&<>
  <div className="search"><Search size={21}/><input aria-label="Tìm phần cần phân loại" placeholder="Ví dụ: hộp xốp, cơm thừa, chai nhựa…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Xóa tìm kiếm" onClick={()=>setQuery('')}><X size={18}/></button>}</div>

  <div className="sorting-options">{matches.map(r=><button key={r.id} disabled={busy} aria-pressed={selected.includes(r.id)} className={'sorting-option '+(selected.includes(r.id)?'chosen':'')} onClick={()=>toggle(r.id)}><span>{r.name}<small>{r.scope}</small></span>{selected.includes(r.id)?<Check size={20}/>:<Plus size={20}/>}</button>)}</div>
  {!matches.length&&<div className="empty card"><p>Chưa có hướng dẫn phù hợp. Thử tên khác hoặc kiểm tra với nơi thu gom; không chọn vật phẩm gần giống.</p><button className="text" onClick={()=>{setQuery('');setGroup('')}}>Xem lại danh mục</button></div>}</>}
  {chosen.length>0&&<div className="card sorting-selection"><h2>Các phần bạn đã chọn</h2>{chosen.map(r=><div className="selected-part" key={r.id}><div><strong>{r.name}</strong><p>{r.scope}</p>{r.group===null&&<p className="needs-detail">Phần này chưa đủ thông tin để xác định nhóm. Chọn lại nếu bạn biết rõ hơn.</p>}{r.special&&<p className="needs-detail">Cần thu gom riêng; không bỏ chung vào thùng rác còn lại.</p>}</div><button className="text" disabled={busy||!selected.includes(r.id)} aria-label={'Bỏ '+r.name} onClick={()=>toggle(r.id)}><X size={18}/></button></div>)}<label className="checkbox"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Tôi đã kiểm tra các phần và điều kiện áp dụng ở trên.</label><button className="primary full" disabled={!confirmed||busy} onClick={submit}>{busy?'Đang mở hướng dẫn…':'Xem cách tách và phân loại'}</button><small>Xác nhận, sửa lựa chọn và xem lại không trừ thêm lượt AI.</small></div>}
  {error&&<div role="alert" className="warning">{error}</div>}
 </div>
}
export function SortingResult({id,onBack,onSuggestions}:{id:string;onBack:()=>void;onSuggestions:()=>void}){
 const [result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;sortingRequest('sorting?id='+encodeURIComponent(id)).then(r=>active&&setResult(r)).catch(e=>active&&setError(e.message));return()=>{active=false}},[id]);
 async function save(){if(busy)return;setBusy(true);try{await sortingRequest('sorting/saved',{id,saved:!result.saved});setResult({...result,saved:!result.saved})}catch(e){setError(e instanceof Error?e.message:'Chưa lưu được.')}finally{setBusy(false)}}
 return <section className="section narrow"><button className="text" onClick={onBack}>Tra cứu khác</button><div className="page-title"><div className="eyebrow">Kết quả phân loại</div><h1>Tách từng phần, bỏ đúng nhóm.</h1><p>Xem lại hướng dẫn này không trừ lượt AI.</p></div>{error&&<div className="warning" role="alert">{error}</div>}{result?<><div className="section-heading"><p>{result.method} · {new Date(result.createdAt).toLocaleDateString('vi-VN')}</p><button className="secondary" disabled={busy} onClick={save}><Bookmark size={18}/>{result.saved?'Bỏ lưu':'Lưu hướng dẫn'}</button></div>{result.updated&&<div className="notice">Nội dung phân loại đã được cập nhật. Bên dưới là hướng dẫn hiện hành.</div>}{!result.plan.complete&&<div className="notice">Có phần chưa đủ thông tin. Chỉ các phần đã xác định rõ mới có nhóm rác; phần còn lại có bước kiểm tra tiếp.</div>}
 {result.plan.components.map((r:SortingRule,i:number)=><article className={'card disposal-part bin-'+(r.group||'unknown')} key={r.id}><div className="eyebrow">Phần {i+1}</div><h2>{r.name}</h2><div className="bin-label">{r.group?SORTING_GROUPS.find(g=>g.id===r.group)?.name:'Cần kiểm tra thêm'}</div>{r.condition&&<p className="classification-condition">{r.condition}</p>}{r.special&&<strong className="separate-collection">Thu gom riêng · chất thải nguy hại</strong>}<ol className="instructions">{r.steps.map(step=><li key={step}>{step}</li>)}</ol>{r.warning&&<p className="part-warning"><AlertTriangle size={18}/>{r.warning}</p>}<small>Áp dụng: {r.scope}</small></article>)}
 <MaterialKnowledge key={id} ruleIds={result.plan.components.map((r:SortingRule)=>r.id)}/>
 {result.product&&result.productGuidance&&<ProductAdvice product={result.product} guidance={result.productGuidance}/>}
 <div className="notice">{result.plan.localNote}</div><details className="card reuse-details"><summary>Gợi ý tái sử dụng, tái chế thêm</summary>{result.plan.components.filter((r:SortingRule)=>r.reuse).map((r:SortingRule)=><p key={r.id}><strong>{r.name}:</strong> {r.reuse}</p>)}<p>Đây là lựa chọn thêm sau khi đã tách và phân loại. Điều kiện tiếp nhận tùy từng nơi.</p><RelatedReading rows={result.relatedArticles||[]}/><button className="text" onClick={onSuggestions}>Xem tất cả Eco Tips</button></details><details className="sorting-source"><summary>Nguồn hướng dẫn</summary><p>Đối chiếu Công văn 9368/BTNMT-KSONMT. {result.plan.components.map((r:SortingRule)=>r.section).join('; ')}.</p><a href={result.plan.source} target="_blank" rel="noreferrer">Đọc hướng dẫn của Bộ TN&amp;MT</a></details></>:!error&&<p role="status">Đang tải kết quả…</p>}</section>
}
export function SortingHistory({savedOnly,onOpen}:{savedOnly:boolean;onOpen:(id:string)=>void}){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);useEffect(()=>{let active=true;sortingRequest('account').then(r=>{if(active){setRows(r.sorting||[]);setLoaded(true)}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[]);const list=rows.filter(r=>!savedOnly||r.saved);return <div className="spaced"><h2>{savedOnly?'Hướng dẫn phân loại đã lưu':'Lịch sử phân loại'}</h2>{error&&<div className="warning">{error}</div>}<div className="grid three">{list.map(r=><button className="card item-card" key={r.id} onClick={()=>onOpen(r.id)}><span><h3>{r.title}</h3><p>{r.method} · {new Date(r.createdAt).toLocaleDateString('vi-VN')}</p><small>Xem lại miễn lượt</small></span></button>)}</div>{loaded&&!list.length&&<p>Chưa có kết quả trong mục này.</p>}</div>}
