// Source-reviewed classification rules. AI may identify visible components;
// only this versioned catalog supplies groups, instructions and exceptions.
export const SORTING_VERSION = 3;
export const SORTING_SOURCE = 'https://vea.mae.gov.vn/Data/files/2023/CV9368/9368-btnmt-kson_Signed.pdf';
export const SORTING_GROUPS = [
 {id:'recycle',name:'Rác tái sử dụng, tái chế',description:'Vật liệu có thể thu hồi như giấy sạch, chai lọ, kim loại.',icon:'recycle'},
 {id:'food',name:'Rác thực phẩm',description:'Thức ăn thừa, rau củ và phần bỏ đi khi chế biến.',icon:'food'},
 {id:'other',name:'Rác sinh hoạt còn lại',description:'Hộp xốp, đồ dùng một lần và các loại khác. Rác nguy hại cần thu gom riêng.',icon:'other'}
] as const;
export type SortGroup = typeof SORTING_GROUPS[number]['id'];
export type SortingRule = {id:string;name:string;keywords:string;group:SortGroup|null;scope:string;steps:string[];warning?:string;reuse?:string;section:string;special?:boolean;condition?:string};
export const SORTING_RULES: SortingRule[] = [
 {id:'tissue',name:'Khăn giấy dính thức ăn',keywords:'khăn giấy ăn đã dùng dính thức ăn bẩn',group:'other',scope:'Khăn giấy đã sử dụng trong ăn uống thông thường; không dính hóa chất hoặc chất thải y tế.',steps:['Nếu có miếng thức ăn dễ tách, lấy riêng phần đó vào rác thực phẩm. Không cần gỡ sạch vụn nhỏ.','Gom khăn giấy đã dùng vào rác sinh hoạt còn lại; không rửa để tái chế, không trộn với giấy sạch.'],section:'3.3.3'},
 {id:'laminated',name:'Giấy, đế bánh có lớp tráng phủ',keywords:'đế bánh gato phủ bạc nhựa giấy nhiều lớp',group:null,scope:'Giấy ghép hoặc phủ nhựa, bạc; chưa rõ cấu tạo và nơi tiếp nhận.',steps:['Tách phần bánh, thức ăn còn lại vào nhóm rác thực phẩm.','Giữ bao bì riêng; kiểm tra nhãn và hỏi nơi thu gom về bao bì nhiều lớp.'],warning:'Chưa có hướng dẫn đã xác minh để tự xếp mọi đế bánh tráng phủ vào một nhóm. Không rửa giấy hoặc coi đây là carton sạch.',section:'1.1.2 (cần xác minh cấu tạo và tình trạng)'},
 {id:'food',name:'Thức ăn thừa, rau củ bỏ đi',keywords:'bánh bánh thừa cơm thịt cá vỏ rau củ quả hữu cơ thực phẩm',group:'food',scope:'Phần thực phẩm đã bỏ đi, tách khỏi bao bì.',steps:['Gạt thức ăn ra khỏi hộp, tách túi và các vật không phải thực phẩm.','Chứa riêng trong vật đựng hoặc túi kín, không rò rỉ; giao theo hướng dẫn thu gom tại nơi ở.'],section:'2.1–2.2'},
 {id:'foam',name:'Hộp xốp đựng thức ăn',keywords:'hộp cơm xốp khay xốp',group:'other',scope:'Hộp xốp thông thường, không chứa hóa chất nguy hại.',steps:['Lấy hết thức ăn bên trong; phần thức ăn để riêng vào nhóm rác thực phẩm.','Gom hộp vào phần rác sinh hoạt còn lại, tránh rơi vãi.'],section:'3.3.3'},
 {id:'metal',name:'Lon, hộp kim loại',keywords:'lon nhôm sắt thiếc đồ hộp cá pate kim loại mỹ phẩm',group:'recycle',scope:'Bao bì thực phẩm, đồ uống hoặc mỹ phẩm thông thường; không chứa chất nguy hại.',steps:['Lấy riêng sản phẩm còn lại bên trong theo hướng dẫn phù hợp.','Thu gọn vỏ lon, hộp; xếp phần sắc nhọn để tránh gây thương tích khi giao thu gom.'],warning:'Bao bì hóa chất nguy hại cần thu gom riêng. Nhóm của nắp và phụ kiện cần xác định riêng.',section:'1.3.1–1.3.3'},
 {id:'bottle',name:'Chai, lọ nhựa',keywords:'chai nước suối nhựa pet mỹ phẩm dầu gội serum hũ kem',group:'recycle',scope:'Chai, lọ nhựa đựng thực phẩm, đồ uống hoặc mỹ phẩm thông thường; không chứa chất nguy hại.',steps:['Tháo nắp, lấy phần chứa bên trong ra theo hướng dẫn phù hợp trước khi thu gom vỏ.','Thu gọn vỏ và giao cho nơi tiếp nhận loại bao bì này.'],warning:'Nắp, vòi bơm được xác định riêng. Không áp dụng cho bao bì hóa chất nguy hại; không mặc định mọi loại nhựa đều tái chế được.',reuse:'Có thể chuyển vỏ đã chuẩn bị cho nơi thu hồi có tiếp nhận loại bao bì này.',section:'1.2.1'},
 {id:'glass',name:'Chai, lọ thủy tinh',keywords:'thủy tinh chai lọ hũ mỹ phẩm serum kem dưỡng thực phẩm đồ uống',group:'recycle',scope:'Chai, lọ thủy tinh đựng thực phẩm, đồ uống hoặc mỹ phẩm thông thường; không nhiễm chất nguy hại.',steps:['Tháo nắp, loại bỏ phần sản phẩm bên trong theo hướng dẫn phù hợp.','Thu xếp gọn, hạn chế va đập gây vỡ và giao cho nơi có tiếp nhận.'],warning:'Không tự xếp nắp hoặc vòi bơm theo thân chai. Nếu chưa kiểm tra tình trạng, quan sát vết nứt trước khi cầm; không áp dụng cho nhiệt kế hay bóng đèn chứa thủy ngân.',reuse:'Chỉ dùng lại chai, lọ còn nguyên vẹn cho mục đích phù hợp với sản phẩm từng chứa.',section:'1.4.1'},
 {id:'paper',name:'Giấy, bìa carton sạch',keywords:'giấy báo vở thùng bìa carton sạch khô',group:'recycle',scope:'Giấy, bao bì giấy không nhiễm bẩn.',steps:['Tách vật chứa và phần không phải giấy ra khỏi bao bì.','Giữ giấy khô, thu gọn và để riêng với rác thực phẩm.'],section:'1.1.1–1.1.2'},
 {id:'dirty-paper',name:'Hộp giấy thấm dầu hoặc bẩn',keywords:'hộp pizza giấy dính dầu mỡ bẩn',group:null,scope:'Giấy có dầu ngấm hoặc nhiễm bẩn, chưa đủ căn cứ để xếp như giấy sạch.',steps:['Lấy riêng thức ăn còn lại vào nhóm rác thực phẩm.','Giữ phần giấy bẩn riêng, hỏi đơn vị thu gom tại nơi ở; chưa xếp mặc định vào nhóm tái chế.'],warning:'Hướng dẫn nền chỉ xác định bao bì giấy không nhiễm bẩn ở nhóm tái chế. EcoSnap chưa có quy tắc địa phương cho phần giấy bẩn này.',section:'1.1.2 (điều kiện không nhiễm bẩn)'},
 {id:'clothes',name:'Quần áo, đồ vải thông thường',keywords:'quần áo cũ vải chăn màn rèm',group:'recycle',scope:'Đồ vải không dính thuốc bảo vệ thực vật, axit, dầu công nghiệp hoặc hóa chất nguy hại.',steps:['Tách đồ nhiễm hóa chất nguy hại khỏi đồ vải thông thường.','Thu gọn đồ vải để chuyển cho nơi có tiếp nhận; giữ đồ sạch, còn dùng được riêng.'],reuse:'Đồ sạch, còn sử dụng tốt có thể cho tặng hoặc dùng tiếp; kiểm tra điều kiện của nơi nhận.',section:'1.5.1'},
 {id:'garden',name:'Bã cà phê, trà và lá cây',keywords:'bã cà phê trà lá cây cành cỏ hữu cơ vườn',group:'other',scope:'Bã thực vật và rác làm vườn trong danh mục hướng dẫn nền.',steps:['Thu gọn, giảm thể tích nếu thuận tiện, chứa để tránh rơi vãi.','Giao theo cách thu gom tại nơi ở; nếu địa phương có thu gom riêng để ủ, làm theo hướng dẫn đó.'],warning:'Có nguồn gốc hữu cơ không đồng nghĩa với nhóm rác thực phẩm. Mục 3.3.1 của hướng dẫn nền xếp các loại này trong nhóm còn lại.',reuse:'Ủ chỉ là phương án thêm khi có cách làm và nơi tiếp nhận phù hợp; không làm thay đổi nhóm trong hướng dẫn nền.',section:'3.3.1'},
 {id:'battery',name:'Pin, ắc quy đã dùng',keywords:'pin tiểu cúc áo ắc quy nguy hại',group:'other',special:true,scope:'Pin, ắc quy thải; thuộc nhánh chất thải nguy hại.',steps:['Giữ nguyên, không tháo hoặc đập; để riêng khỏi rác thông thường.','Chuyển tới điểm thu gom chất thải nguy hại có tiếp nhận pin.'],warning:'Không bỏ chung vào thùng rác còn lại. Pin phồng, nóng hoặc rò rỉ cần hướng dẫn của đơn vị tiếp nhận; không tự tháo khỏi thiết bị.',section:'3.1.3'},
 {id:'hazardous',name:'Bao bì hóa chất nguy hại',keywords:'hóa chất thuốc trừ sâu dầu công nghiệp axit',group:'other',special:true,scope:'Bao bì còn hoặc từng chứa hóa chất có thành phần nguy hại.',steps:['Giữ trong vật chứa an toàn, kín; không đổ phần dư xuống cống hoặc trộn với rác khác.','Liên hệ nơi thu gom chất thải nguy hại để bàn giao.'],warning:'Thu gom riêng, không cho chung vào thùng tái chế hoặc rác còn lại thông thường.',section:'3.1.1'},
 {id:'single-use',name:'Hộp, khay và đồ nhựa dùng một lần',keywords:'hộp bánh khay hộp nhựa ống hút thìa muỗng nĩa nhựa dùng một lần',group:'other',scope:'Sản phẩm nhựa dùng một lần thông thường theo danh mục nền.',steps:['Tách thức ăn còn bám vào nhóm rác thực phẩm.','Gom phần đồ nhựa dùng một lần vào rác sinh hoạt còn lại, tránh rơi vãi.'],section:'3.3.3'},
 {id:'plastic-container',name:'Hộp, khay nhựa đựng thực phẩm',keywords:'hộp bánh hộp cơm khay nhựa thực phẩm',group:null,scope:'Đã nhận ra hộp hoặc khay nhựa đựng thực phẩm, nhưng chưa rõ loại bao bì và điều kiện tiếp nhận.',steps:['Tách phần bánh, thức ăn khỏi hộp; phần thực phẩm bỏ đi để riêng.','Nếu là đồ nhựa dùng một lần, chọn mục tương ứng. Với loại hộp khác, kiểm tra ký hiệu và hỏi nơi thu gom trước khi cho vào nhóm tái chế.'],warning:'Không cần biết nhãn hiệu để tách bánh và hộp. Không suy ra mã nhựa hoặc khả năng tái chế chỉ từ ảnh.',section:'1.2.1 và 3.3.3'},
 {id:'unknown-container',name:'Bao bì cần kiểm tra thêm',keywords:'hộp nhựa giấy kim loại chai lọ hũ chưa rõ',group:null,scope:'Chưa đủ thông tin về vật liệu hoặc sản phẩm từng chứa trong bao bì.',steps:['Giữ bao bì riêng; xem nhãn để xác định vật liệu và sản phẩm từng chứa.','Nếu chưa xác định được, hỏi đơn vị thu gom hoặc nhà sản xuất trước khi tháo, đổ hay rửa.'],warning:'Không mặc định bao bì đã rỗng là an toàn để tái chế.',section:'Các nhóm 1–3; cần xác định vật liệu và sản phẩm'},
 {id:'unknown-liquid',name:'Chất lỏng chưa rõ trong chai',keywords:'nước chất lỏng chai',group:null,scope:'Chưa biết chất chứa trong chai.',steps:['Giữ kín chai và xác định chất chứa từ nhãn hoặc nguồn sử dụng.','Không đổ bỏ khi chưa rõ là đồ uống, dầu hay hóa chất; hỏi nơi tiếp nhận nếu không xác định được.'],section:'1.2.1 và 3.1.1'},
 {id:'glass-broken',name:'Thân thủy tinh nứt hoặc vỡ',keywords:'chai lọ hũ thủy tinh nứt vỡ mảnh',group:'recycle',scope:'Thủy tinh thông thường, không nhiễm chất nguy hại; không phải đèn hay nhiệt kế chứa thủy ngân.',steps:['Thu xếp, chứa phần sắc nhọn an toàn để tránh gây thương tích khi phân loại và thu gom.','Giao riêng theo hướng dẫn của nơi tiếp nhận; tránh làm vỡ thêm.'],section:'1.4.3'},
 {id:'product-residue',name:'Mỹ phẩm còn dư',keywords:'kem serum dầu gội dầu xả mỹ phẩm còn dư',group:null,scope:'Phần mỹ phẩm còn lại cần hướng dẫn xử lý riêng theo sản phẩm.',steps:['Giữ sản phẩm trong vật chứa; kiểm tra tên và thông tin trên nhãn.','Hỏi nhà sản xuất hoặc đơn vị thu gom về cách xử lý phần dư trước khi đổ bỏ hay rửa vỏ.'],warning:'Chưa có quy tắc chung cho mọi mỹ phẩm dư. Không xếp phần dư vào rác thực phẩm hoặc mặc định đổ xuống cống.',section:'1.2.1, 1.3.1, 1.4.1 (yêu cầu loại bỏ phần chứa; xử lý phần dư cần xác minh)'},
 {id:'drink-residue',name:'Phần chứa còn lại trong chai, lọ',keywords:'đồ uống nước thực phẩm còn lại',group:null,scope:'Phần chứa được mô tả là thực phẩm hoặc đồ uống nhưng chưa xác định cách xử lý riêng.',steps:['Xác định phần chứa còn lại là nước uống, đồ uống khác hay thực phẩm.','Chọn hướng dẫn phù hợp cho phần chứa trước khi gom vỏ; chưa coi toàn bộ chai, lọ là một loại rác.'],section:'1.2.1, 1.3.1, 1.4.1'},
 {id:'unknown-accessory',name:'Nắp, vòi bơm và phụ kiện',keywords:'nắp vòi bơm ống hút phụ kiện hỗn hợp',group:null,scope:'Chưa xác định cấu tạo hoặc nơi tiếp nhận phụ kiện.',steps:['Xem nắp hoặc vòi bơm là nhựa, kim loại hay gồm nhiều vật liệu; không tự tháo rã bộ phận khó tách.','Kiểm tra yêu cầu của nơi tiếp nhận vỏ chai; giữ phụ kiện riêng nếu chưa có hướng dẫn phù hợp.'],warning:'Phụ kiện chưa rõ không làm mất kết quả của thân chai đã xác định. Không tự coi phụ kiện cùng nhóm với thân chai.',section:'1.2.1, 1.3.1, 1.4.1 (tháo nắp; phụ kiện cần xác định riêng)'},
 {id:'plastic-bag',name:'Túi nhựa thông thường đã rỗng',keywords:'túi nhựa bao bì nhựa nilon sạch',group:'recycle',scope:'Túi nhựa thông thường đã loại bỏ phần chứa; không nhiễm chất nguy hại.',steps:['Loại bỏ phần chứa trước khi gom túi.','Thu gọn và chuyển cho nơi tiếp nhận loại túi này.'],section:'1.2.1'},
 {id:'electronics',name:'Thiết bị điện, điện tử',keywords:'điện thoại máy tính đồ điện điện tử bàn phím',group:'recycle',scope:'Thiết bị điện, điện tử trong danh mục hướng dẫn nền.',steps:['Giữ nguyên hình dạng, không tự tháo dời.','Chuyển cho nơi có tiếp nhận thiết bị điện, điện tử để thu hồi.'],section:'1.8.1–1.8.2'},
 {id:'lamp',name:'Đèn huỳnh quang, nhiệt kế thủy ngân',keywords:'đèn huỳnh quang nhiệt kế thủy ngân nguy hại',group:'other',special:true,scope:'Chất thải thuộc nhánh nguy hại, cần thu gom riêng.',steps:['Không đập vỡ; để riêng khỏi rác sinh hoạt thông thường.','Nếu đã vỡ, lưu giữ an toàn, tránh gây thương tích và phát tán thủy ngân; liên hệ nơi thu gom chất thải nguy hại.'],section:'3.1.2'},
 {id:'hazardous-fabric',name:'Đồ vải dính hóa chất nguy hại',keywords:'vải giẻ lau dầu công nghiệp hóa chất',group:'other',special:true,scope:'Đồ vải, giẻ lau dính dầu công nghiệp hoặc hóa chất nguy hại.',steps:['Chứa riêng, tránh phát tán chất bám ra ngoài.','Liên hệ nơi thu gom chất thải nguy hại; không gom với quần áo thông thường.'],section:'3.1.1'},
 {id:'unknown-item',name:'Đồ vật chưa đủ thông tin',keywords:'không rõ khác chưa biết',group:null,scope:'Chưa có hướng dẫn phù hợp với đồ vật hoặc tình trạng.',steps:['Kiểm tra tên, vật liệu và sản phẩm từng chứa hoặc chất đang bám trên đồ vật.','Hỏi nơi thu gom về trường hợp cụ thể; không chọn một đồ vật gần giống để thay thế.'],section:'Hướng dẫn các nhóm 1–3; cần xác định trường hợp'}
];
export const SORTING_PRESETS=[
 {name:'Hộp cơm xốp còn thức ăn',ids:['foam','food']},
 {name:'Đồ hộp kim loại còn thức ăn',ids:['metal','food']},
 {name:'Chai nhựa chưa rõ chất lỏng',ids:['bottle','unknown-liquid']}
];
export const normalizeSearch=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
export function sortingPlan(ids:string[]){
 const shells=['bottle','glass','metal','glass-broken'];
 const knownIds=ids.map(id=>SORTING_RULES.some(r=>r.id===id)?id:'unknown-item');
 const safeIds=knownIds.includes('unknown-liquid')?knownIds.map(id=>shells.includes(id)?'unknown-container':id):knownIds;
 const residue=ids.some(id=>['product-residue','drink-residue'].includes(id));
 const components=[...new Set(safeIds)].map(id=>SORTING_RULES.find(r=>r.id===id)).filter((r):r is SortingRule=>!!r).map(r=>residue&&shells.includes(r.id)?{...r,condition:'Nhóm của vỏ sau khi phần chứa được xác minh và xử lý phù hợp.',steps:[...(r.id==='glass-broken'?[r.steps[0]]:[]),'Giữ nguyên phần chứa khi chưa có hướng dẫn xử lý; xem mục phần còn dư bên dưới.','Sau khi đã xử lý phần chứa phù hợp, chuẩn bị vỏ theo hướng dẫn của nơi tiếp nhận.']}:r).sort((a,b)=>(a.group==='food'?-2:a.special?-1:0)-(b.group==='food'?-2:b.special?-1:0));
 return {version:SORTING_VERSION,complete:components.length>0&&components.every(r=>r.group!==null&&!r.condition),components,source:SORTING_SOURCE,localNote:'Tên nhóm theo hướng dẫn nền toàn quốc. Cách chứa, lịch thu gom và nơi tiếp nhận thực hiện theo hướng dẫn tại nơi bạn ở.'};
}
