import {legacyGuideStatus,retireGuides} from '../../../../lib/server/retire-guides';
import {SORTING_RULES,SORTING_VERSION,SORTING_GROUPS,SORTING_PRESETS,SORTING_SOURCE} from '../../../../lib/sorting-rules';
import {saveSorting,readSorting,sortingHistory} from '../../../../lib/server/sorting';
import {recognizeImage,recognitionResult,confirmRecognition} from '../../../../lib/server/recognition';
import {LIVE_OPENAI_ENABLED,MIN_RESERVE_VND} from '../../../../lib/server/ai-policy';
import {database,statement,bucket,runtime,periods} from '../../../../lib/server/database';
import {authClient,configured,identity,requireAdmin,HttpError,checkOrigin,baseURL,safeReturn} from '../../../../lib/server/auth';
import {getSettings,quota,budgetState,requestRow} from '../../../../lib/server/quota';
import {json,str,number,limit,validateFile,boundedBody,password as validatePassword} from '../../../../lib/server/security';
export const dynamic='force-dynamic';
const kinds=['items','articles','points','projects','groups'];
const subjects=['Câu hỏi chung','Báo kết quả sai','Cập nhật điểm thu gom','Chia sẻ dự án','Góp ý giao diện'];
function unpack(row:any){return {...JSON.parse(row.payload),id:row.id,title:row.title,name:row.title,group:row.group_name,published:!!row.published,verified:!!row.verified,source:row.source,version:row.version,kind:row.kind}}
async function handle(req:Request){const out=new Headers({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});const respond=(data:any,status=200)=>Response.json(data,{status,headers:out});try{checkOrigin(req);const url=new URL(req.url),path=url.pathname.replace(/^\/api\/ecosnap\//,'');const method=req.method;
 if(path==='status')return respond({authConfigured:configured(),aiEnabled:LIVE_OPENAI_ENABLED,adminConfigured:!!runtime().ECOSNAP_ADMIN_EMAIL});
 if(path==='me'){const u=await identity(req,out,false);return respond({user:u,authConfigured:configured(),quota:u?await quota(u.id):null})}
 if(path==='auth/callback'){const client=authClient(req,out),code=url.searchParams.get('code');if(!code)throw new HttpError(400,'Liên kết xác thực không hợp lệ.');const {error}=await client.auth.exchangeCodeForSession(code);if(error)throw new HttpError(400,'Liên kết xác thực đã hết hạn hoặc không hợp lệ. Vui lòng thử lại trên trình duyệt đã bắt đầu thao tác.');out.set('Location',baseURL+'/#'+safeReturn(url.searchParams.get('next')));return new Response(null,{status:303,headers:out})}
 if(path.startsWith('auth/')&&method==='POST'){await limit('auth:'+req.headers.get('cf-connecting-ip'),20,600000);const client=authClient(req,out),action=path.split('/')[1],data=await json(req),next=safeReturn(data.next),redirect=baseURL+'/api/ecosnap/auth/callback?next='+encodeURIComponent(next);if(action==='google'){const r=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect,skipBrowserRedirect:true}});if(r.error||!r.data.url)throw new HttpError(503,'Đăng nhập Google chưa sẵn sàng. Vui lòng kiểm tra cấu hình nhà cung cấp.');return respond({url:r.data.url})}if(action==='logout'){const r=await client.auth.signOut();if(r.error)throw new HttpError(503,'Chưa đăng xuất được. Vui lòng thử lại.');return respond({ok:true})}if(action==='reset'){await identity(req,out);const password=validatePassword(data.password);if(password.length<10)throw new HttpError(400,'Mật khẩu cần ít nhất 10 ký tự.');const r=await client.auth.updateUser({password});if(r.error)throw new HttpError(400,'Không cập nhật được mật khẩu. Hãy yêu cầu liên kết mới.');return respond({ok:true,message:'Đã cập nhật mật khẩu.'})}const email=str(data.email,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpError(400,'Email không hợp lệ.');if(action==='forgot'){const r=await client.auth.resetPasswordForEmail(email,{redirectTo:baseURL+'/api/ecosnap/auth/callback?next=%2Freset'});if(r.error)throw new HttpError(503,'Chưa gửi được yêu cầu khôi phục. Vui lòng thử lại sau.');return respond({message:'Nếu email có tài khoản, bạn sẽ nhận được hướng dẫn khôi phục. Mở liên kết trên trình duyệt này.'})}const password=validatePassword(data.password);if(action==='signup'){if(password.length<10)throw new HttpError(400,'Mật khẩu cần ít nhất 10 ký tự.');const r=await client.auth.signUp({email,password,options:{emailRedirectTo:redirect}});if(r.error)throw new HttpError(400,'Chưa tạo được tài khoản. Kiểm tra thông tin hoặc thử lại sau.');return respond({message:'Vui lòng kiểm tra email xác minh và mở liên kết trên trình duyệt này. Nếu đã có tài khoản, hãy đăng nhập.'})}if(action==='login'){const r=await client.auth.signInWithPassword({email,password});if(r.error)throw new HttpError(401,'Email hoặc mật khẩu chưa đúng, hoặc email chưa được xác minh.');return respond({ok:true,next})}throw new HttpError(404,'Không có thao tác này.')}
 if(path==='content'&&method==='GET'){const kind=url.searchParams.get('kind')||'articles';if(!kinds.includes(kind))throw new HttpError(400,'Danh mục không hợp lệ.');if(kind==='items'||kind==='groups')await identity(req,out);const result=await statement('SELECT * FROM content WHERE kind=? AND published=1 AND verified=1 ORDER BY updated_at DESC',kind).all();return respond({rows:result.results.map(unpack)})}
 if(path==='account'&&method==='GET'){const u=await identity(req,out);const [h,s]=await Promise.all([statement('SELECT h.id,h.item_id,h.method,h.created_at,c.title FROM history h JOIN content c ON c.id=h.item_id WHERE h.user_id=? ORDER BY h.created_at DESC LIMIT 200',u.id).all(),statement('SELECT s.item_id,s.created_at,c.title FROM saved s JOIN content c ON c.id=s.item_id WHERE s.user_id=? ORDER BY s.created_at DESC',u.id).all()]);return respond({history:h.results,saved:s.results,sorting:await sortingHistory(u.id),quota:await quota(u.id)})}
 if(path==='history'&&method==='POST'){const u=await identity(req,out),data=await json(req),id=str(data.itemId,100);await limit('history:'+u.id,60,60000);const item=await statement("SELECT id FROM content WHERE id=? AND kind='items' AND published=1 AND verified=1",id).first();if(!item)throw new HttpError(404,'Vật phẩm chưa được xuất bản.');await statement("INSERT INTO history(id,user_id,item_id,method,created_at) VALUES(?,?,?,'Thủ công',?)",crypto.randomUUID(),u.id,id,Date.now()).run();return respond({ok:true})}
 if(path==='saved'&&(method==='POST'||method==='DELETE')){const u=await identity(req,out),data=await json(req),id=str(data.itemId,100);if(method==='POST'){const item=await statement("SELECT id FROM content WHERE id=? AND kind='items' AND published=1 AND verified=1",id).first();if(!item)throw new HttpError(404,'Vật phẩm chưa được xuất bản.');await statement('INSERT INTO saved(user_id,item_id,created_at) VALUES(?,?,?) ON CONFLICT(user_id,item_id) DO NOTHING',u.id,id,Date.now()).run()}else await statement('DELETE FROM saved WHERE user_id=? AND item_id=?',u.id,id).run();return respond({ok:true})}
 if(path==='sorting/catalog'&&method==='GET'){await identity(req,out);return respond({version:SORTING_VERSION,rules:SORTING_RULES,groups:SORTING_GROUPS,presets:SORTING_PRESETS,source:SORTING_SOURCE})}
 if(path==='sorting'&&method==='POST'){const u=await identity(req,out);await limit('sorting:'+u.id,60,60000);return respond(await saveSorting(u.id,await json(req)))}
 if(path==='sorting'&&method==='GET'){const u=await identity(req,out);return respond(await readSorting(u.id,str(url.searchParams.get('id'),100)))}
 if(path==='sorting/saved'&&method==='POST'){const u=await identity(req,out),d=await json(req),id=str(d.id,100);if(typeof d.saved!=='boolean')throw new HttpError(400,'Trạng thái lưu không hợp lệ.');await readSorting(u.id,id);await statement('UPDATE sorting_results SET saved=? WHERE id=? AND user_id=?',d.saved?1:0,id,u.id).run();return respond({ok:true})}
 if(path==='recognize'&&method==='POST'){const u=await identity(req,out);const result=await recognizeImage(req,u.id);return respond(result,result.status==='pending'?202:200)}
 if(path==='recognition'&&method==='GET'){const u=await identity(req,out);const id=url.searchParams.get('id');if(id)return respond(await recognitionResult(u.id,str(id,100)));const row=await requestRow(u.id,str(url.searchParams.get('key'),100));if(!row)throw new HttpError(404,'Yêu cầu chưa được tiếp nhận. Bạn có thể gửi lại.');return respond(await recognitionResult(u.id,row.id))}
 if(path==='recognition/confirm'&&method==='POST'){const u=await identity(req,out),d=await json(req);return respond(await confirmRecognition(u.id,str(d.requestId,100),str(d.itemId,100),number(d.version,1,1e9)))}
 if(path==='feedback'&&method==='POST'){if(Number(req.headers.get('content-length')||0)>6*1024*1024)throw new HttpError(413,'Dữ liệu quá lớn.');await limit('feedback-ip:'+req.headers.get('cf-connecting-ip'),5,3600000);const bytes=await boundedBody(req,6*1024*1024);const form=await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData();if(form.get('website'))throw new HttpError(400,'Yêu cầu không hợp lệ.');const name=str(form.get('name'),100),email=str(form.get('email'),254),subject=str(form.get('subject'),100),message=str(form.get('message'),5000),requestKey=str(form.get('requestKey'),100);if(!/^[\w-]{16,100}$/.test(requestKey)||!subjects.includes(subject)||!/^\S+@\S+\.\S+$/.test(email))throw new HttpError(400,'Vui lòng kiểm tra email và chủ đề.');await limit('feedback-email:'+email.toLowerCase(),5,3600000);const existing=await statement('SELECT id FROM feedback WHERE request_key=?',requestKey).first();if(existing)return respond({ok:true});const f=form.get('file');let file:File|null=null,key:string|null=null;const id=crypto.randomUUID();if(f instanceof File&&f.size){file=await validateFile(f);key='feedback/'+id;await bucket().put(key,file.stream(),{httpMetadata:{contentType:file.type}})}try{await statement('INSERT INTO feedback(id,name,email,subject,message,file_key,file_name,file_type,file_size,created_at,request_key) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,name,email,subject,message,key,file?.name.slice(0,200)||null,file?.type||null,file?.size||null,Date.now(),requestKey).run()}catch(e){if(key)await bucket().delete(key);throw e}return respond({ok:true,message:'Đã lưu góp ý. Cảm ơn bạn!'})}
 if(path.startsWith('admin/')){const actor=await requireAdmin(req,out),part=path.slice(6);if(part==='overview'){const month=periods().month,s=await getSettings();const [usage,fs,us]=await Promise.all([budgetState(),statement("SELECT COUNT(*) n FROM feedback WHERE status!='Đã xử lý'").first(),statement('SELECT COUNT(*) n FROM users').first()]);return respond({settings:s,usage,feedback:fs,users:us,aiEnabled:LIVE_OPENAI_ENABLED})}
 if(part==='legacy-guides'&&method==='GET')return respond(await legacyGuideStatus());
 if(part==='legacy-guides'&&method==='POST'){const d=await json(req);return respond(await retireGuides(actor.id,d.confirmed))}
 if(part==='content'&&method==='GET'){const rows=await statement('SELECT * FROM content ORDER BY updated_at DESC LIMIT 1000').all();return respond({rows:rows.results.map(unpack)})}
 if(part==='content'&&method==='POST'){const d=await json(req);const kind=str(d.kind,20),id=d.id?str(d.id,100):crypto.randomUUID(),title=str(d.title,250),groupName=str(d.group||'',100,false),source=str(d.source||'',2000,false);if(!kinds.includes(kind))throw new HttpError(400,'Danh mục không hợp lệ.');if(d.published&&!d.verified)throw new HttpError(400,'Phải kiểm duyệt nội dung trước khi xuất bản.');if(d.published&&!source)throw new HttpError(400,'Cần nguồn hoặc căn cứ kiểm duyệt trước khi xuất bản.');const p=d.payload||{};const clean:Record<string,string>={};for(const k of ['description','summary','body','category','district','materials','address','hours','phone','checkedAt','url','steps','reuse','warning','treatment'])clean[k]=str(p[k]||'',k==='body'?20000:5000,false);if(clean.url&&!/^https:\/\//.test(clean.url))throw new HttpError(400,'Liên kết cần bắt đầu bằng https://');const existing=await statement('SELECT version FROM content WHERE id=?',id).first<any>();if(existing){const version=number(d.version,1,1e9);const r=await statement('UPDATE content SET kind=?,title=?,group_name=?,payload=?,published=?,verified=?,source=?,version=version+1,updated_at=? WHERE id=? AND version=? RETURNING id',kind,title,groupName,JSON.stringify(clean),d.published?1:0,d.verified?1:0,source,Date.now(),id,version).first();if(!r)throw new HttpError(409,'Nội dung đã được thay đổi. Hãy tải lại trước khi lưu.')}else await statement('INSERT INTO content(id,kind,title,group_name,payload,published,verified,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',id,kind,title,groupName,JSON.stringify(clean),d.published?1:0,d.verified?1:0,source,Date.now()).run();await statement('INSERT INTO audit(id,actor_id,action,target,details,created_at) VALUES(?,?,?,?,?,?)',crypto.randomUUID(),actor.id,'content.save',id,JSON.stringify({published:!!d.published}),Date.now()).run();return respond({ok:true,id})}
 if(part==='feedback'&&method==='GET'){const rows=await statement('SELECT id,name,email,subject,message,status,file_name,file_size,created_at FROM feedback ORDER BY created_at DESC LIMIT 500').all();return respond({rows:rows.results})}
 if(part==='feedback'&&method==='PATCH'){const d=await json(req);if(!['Mới','Đang xử lý','Đã xử lý'].includes(d.status))throw new HttpError(400,'Trạng thái không hợp lệ.');await statement('UPDATE feedback SET status=? WHERE id=?',d.status,str(d.id,100)).run();return respond({ok:true})}
 if(part.startsWith('file/')&&method==='GET'){const id=part.slice(5),row=await statement('SELECT file_key,file_name,file_type FROM feedback WHERE id=?',id).first<any>();if(!row?.file_key)throw new HttpError(404,'Không có tệp.');const obj=await bucket().get(row.file_key);if(!obj)throw new HttpError(404,'Không có tệp.');out.set('Content-Type',row.file_type);out.set('Content-Disposition',"attachment; filename*=UTF-8''"+encodeURIComponent(row.file_name));out.set('Content-Security-Policy',"default-src 'none'; sandbox");return new Response(obj.body,{headers:out})}
 if(part==='users'&&method==='GET'){const rows=await statement('SELECT id,email,name,role,created_at FROM users ORDER BY created_at DESC LIMIT 200').all();const enriched=await Promise.all(rows.results.map(async(u:any)=>({...u,quota:await quota(u.id)})));return respond({rows:enriched})}
 if(part==='grants'&&method==='POST'){throw new HttpError(409,'Hạn mức hiện hành cố định ở 5 lượt/ngày và 20 lượt/tháng; chưa áp dụng lượt bổ sung.')}
 if(part==='settings'&&method==='POST'){const d=await json(req);await getSettings();const args=[number(d.dailyLimit,5,5),number(d.monthlyLimit,20,20),number(d.budgetVnd,0,5000000),number(d.reserveVnd,MIN_RESERVE_VND,100000),number(d.version,1,1e9)];const changed=await statement("UPDATE settings SET daily_limit=?,monthly_limit=?,budget_vnd=?,reserve_vnd=?,version=version+1 WHERE id='main' AND version=? RETURNING id",...args).first();if(!changed)throw new HttpError(409,'Cấu hình đã thay đổi. Vui lòng tải lại.');await statement('INSERT INTO audit(id,actor_id,action,target,details,created_at) VALUES(?,?,?,?,?,?)',crypto.randomUUID(),actor.id,'settings.save','main',JSON.stringify(args.slice(0,4)),Date.now()).run();return respond({ok:true})}
 }
 throw new HttpError(404,'Không tìm thấy chức năng.');
 }catch(e){if(e instanceof HttpError)return respond({error:e.message},e.status);console.error('EcoSnap request failed',{type:e instanceof Error?e.name:'unknown'});return respond({error:'Dịch vụ tạm thời không khả dụng. Dữ liệu chưa lưu sẽ được giữ trên biểu mẫu để bạn thử lại.'},503)}}
export const GET=handle;export const POST=handle;export const PATCH=handle;export const DELETE=handle;
